image: node:10

stages:
  - setup
  - test
  - build
  - publish

prepare:
  stage: setup
  variables:
    npm_config_cache: $CI_PROJECT_DIR/cache/
  cache:
    key: npm-${CI_COMMIT_REF_SLUG}
    paths:
      - cache/
  script:
    - npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
    - npm ci
  artifacts:
    paths:
      - node_modules
    expire_in: 1 hour

lint:
  stage: test
  script:
    - npm run lint
    - npm run prettier

test:
  stage: test
  script:
    - npm run test:ci

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 week

publish:
  stage: publish
  script:
    - npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
    - npm --no-git-tag-version version $CI_COMMIT_TAG
    - npm publish
  only:
    - tags
  dependencies:
    - build
